### seq2seq

In [29]:
import sys
sys.path.append('..')
import os
import numpy as np

id_to_char = {}
char_to_id = {}

def _update_vocab(txt):   # 16+75  
    chars = list(txt)     # ['1','6','+','7','5',' ',' ']
#     print(chars)

    for i, char in enumerate(chars):
        if char not in char_to_id:
            tmp_id = len(char_to_id)
            char_to_id[char] = tmp_id
            id_to_char[tmp_id] = char

def load_data(file_name='addition.txt', seed=1984):
#     print(__file__)
#     file_path = os.path.dirname(os.path.abspath(__file__)) + '/' + file_name

#     print(file_path)
#     if not os.path.exists(file_path):
#         print('No file: %s' % file_name)
#         return None

    questions, answers = [], []

    for line in open("../dataset/addition.txt", 'r'):
        idx = line.find('_')           # 16+75  _91  
        questions.append(line[:idx])
        answers.append(line[idx:-1])

#     print(questions[0])
#     print(answers[0])
    
#     print(len(questions))
    
    # 어휘 사전 생성
    for i in range(len(questions)):
        q, a = questions[i], answers[i]
        _update_vocab(q)
        _update_vocab(a)
        
#     print(char_to_id)
#     print(id_to_char)

    # 넘파이 배열 생성
    x = numpy.zeros((len(questions), len(questions[0])), dtype=np.int32) # (50000,7)
    t = numpy.zeros((len(questions), len(answers[0])), dtype=np.int32)   # (50000,5)
    
#     print(x.shape)
#     print(t.shape)

    for i, sentence in enumerate(questions):
        x[i] = [char_to_id[c] for c in list(sentence)]
    for i, sentence in enumerate(answers):
        t[i] = [char_to_id[c] for c in list(sentence)]

#     print(x[0])
#     print(t[0])
    
    # 뒤섞기
    indices = numpy.arange(len(x))
    if seed is not None:
        numpy.random.seed(seed)
    numpy.random.shuffle(indices)
    x = x[indices]
    t = t[indices]
    
#     print(x[0])
#     print(t[0])    

    # 검증 데이터셋으로 10% 할당
    split_at = len(x) - len(x) // 10
    (x_train, x_test) = x[:split_at], x[split_at:]
    (t_train, t_test) = t[:split_at], t[split_at:]

    return (x_train, t_train), (x_test, t_test)

def get_vocab():
    return char_to_id, id_to_char

In [37]:
# coding: utf-8
import sys
sys.path.append('..')
# from dataset import sequence


(x_train, t_train), (x_test, t_test) = load_data('addition.txt', seed=1984)
char_to_id, id_to_char = get_vocab()

print(char_to_id)
print(x_train.shape, t_train.shape)
print(x_test.shape, t_test.shape)
# (45000, 7) (45000, 5)
# (5000, 7) (5000, 5)

print(x_train[0])
print(t_train[0])
# [ 3  0  2  0  0 11  5]
# [ 6  0 11  7  5]

print(''.join([id_to_char[c] for c in x_train[0]]))
print(''.join([id_to_char[c] for c in t_train[0]]))
# 71+118
# _189

{'1': 0, '6': 1, '+': 2, '7': 3, '5': 4, ' ': 5, '_': 6, '9': 7, '2': 8, '0': 9, '3': 10, '8': 11, '4': 12}
(45000, 7) (45000, 5)
(5000, 7) (5000, 5)
[ 3  0  2  0  0 11  5]
[ 6  0 11  7  5]
71+118 
_189 
